version: '3'

volumes:
    db_vol:
      name: db_vol
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/username/data/mariadb
    wp_vol:
      name: wp_vol
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/username/data/wordpress
networks:
  inception:
    driver: bridge
services:
    mariadb:
      container_name: mariadb
      image: mariadb
      build: ./requirements/mariadb
      restart: always
      networks:
        - inception

    wordpress:
      depends_on:
        - mariadb
      container_name: wordpress
      image: wordpress
      build: ./requirements/wordpress
      volumes:
        - wp_vol:/var/www/wordpress
      restart: always
      networks:
        - inception

    nginx:
      depends_on:
        - wordpress
      container_name: nginx
      image: nginx
      build: ./requirements/nginx
      volumes:
        - wp_vol:/var/www/wordpress
      ports: 
        - "443:443"
      networks:
        - inception
      restart: always #When container shut down, restarts automatically.
