version: '3'

volumes:
    mariadb_volume:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/username/data/mariadb
    wordpress_volume:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/username/data/wordpress
networks:
  inception:
    driver: bridge
services:
    mariadb:
      container_name: mariadb
      image: mariadb
      build: ./requirements/mariadb
      restart: always

    wordpress:
      container_name: wordpress
      image: wordpress
      build: ./requirements/wordpress
      volumes:
        - wordpress_volume:/var/www/wordpress
      restart: always

    nginx:
      container_name: nginx
      image: nginx
      build: ./requirements/nginx
      volumes:
        - wordpress_volume:/var/www/wordpress
      ports: 
        - "443:443"
      restart: always #When container shut down, restarts automatically.
